[workspace]
members = [
  "teletypewriter",
  "colors",
  "config",
  "rio"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Raphael Amorim <rapha850@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/raphamorim/rio"
documentation = "https://github.com/raphamorim/rio#readme"

[workspace.dependencies]
wgpu = "0.15.1"
serde = { version = "1.0.158", features = ["derive"] }
bytemuck = { version = "1.9", features = [ "derive" ] }
# teletypewriter = { version = "1.0.5" }
teletypewriter = { path = "teletypewriter" }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
incremental = false

[profile.dev]
# https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/
split-debuginfo = "unpacked"
lto = false
incremental = true
opt-level = 0
