[workspace]
members = [
  "teletypewriter",
  "sugarloaf",
  "corcovado",
  "copa",
  "rio-proc-macros",
  "rio-backend",
  "rio-window",
  "wa",
  "frontends/rioterm"
]
resolver = "2"

[workspace.package]
version = "0.1.18"
authors = ["Raphael Amorim <rapha850@gmail.com>"]
edition = "2021"
license = "MIT"
keywords = ["graphics", "terminal", "application"]
rust-version = "1.82.0"
repository = "https://github.com/raphamorim/rio"
homepage = "https://raphamorim.io/rio"
documentation = "https://github.com/raphamorim/rio#readme"

[workspace.dependencies]
# Note: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations
# Sugarloaf example uses path when used locally, but uses
# version from crates.io when published.
sugarloaf = { path = "sugarloaf", version = "0.1.18" }
teletypewriter = { path = "teletypewriter", version = "0.1.18" }
rio-backend = { path = "rio-backend", version = "0.1.18" }
rio-window = { path = "rio-window", version = "0.1.18", default-features = false }

# Own dependencies
# copa = { path = "copa", default-features = false, version = "0.1.14" }
rio-proc-macros = { path = "rio-proc-macros", version = "0.1.17" }
corcovado = { path = "corcovado", version = "0.1.17" }
copa = { default-features = false, version = "0.1.14" }
wa = { path = "wa", version = "0.1.7" }

raw-window-handle = { version = "0.6.2", features = ["std"] }
parking_lot = { version = "0.12.3", features = ["nightly", "hardware-lock-elision"] }
rustc-hash = "2.0.0"
unicode-width = "0.2.0"
base64 = "0.22.1"
image_rs = { package = "image", version = "0.25.2", default-features = false, features = ["gif", "jpeg", "ico", "png", "pnm", "webp", "bmp"] }
regex = "1.11.0"
bytemuck = { version = "1.17.0", features = [ "derive" ] }
swash = "0.1.18"
serde = { version = "1.0.208", features = ["derive"] }
wgpu = "22.1.0"
libc = "0.2.161"
smol_str = "0.3.1"
futures = "0.3.31"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.34"
wasm-bindgen-test = "0.3.42"
env_logger = "0.11.3"
console_log = "0.2.2"
bitflags = "2.6.0"
iovec = "0.1.4"
console_error_panic_hook = "0.1.7"
tracing = "0.1.40"
objc = "0.2.7"

[profile.release]
lto = true
strip = true
debug = "limited"
codegen-units = 1
incremental = false

[profile.dev]
split-debuginfo = "unpacked"
lto = false
incremental = true
opt-level = 0
