[workspace]
members = [
  "teletypewriter",
  "sugarloaf",
  "corcovado",
  "copa",
  "rio-proc-macros",
  "rio-backend",
  "wa",
  "frontends/rioterm"
]
resolver = "2"

[workspace.package]
version = "0.1.9"
authors = ["Raphael Amorim <rapha850@gmail.com>"]
edition = "2021"
license = "MIT"
keywords = ["graphics", "terminal", "application"]
rust-version = "1.80.1"
repository = "https://github.com/raphamorim/rio"
homepage = "https://raphamorim.io/rio"
documentation = "https://github.com/raphamorim/rio#readme"

[workspace.dependencies]
# Note: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations
# Sugarloaf example uses path when used locally, but uses
# version from crates.io when published.
sugarloaf = { path = "sugarloaf", version = "0.1.9" }
corcovado = { path = "corcovado", version = "0.1.9" }
rio-config = { path = "rio-config", version = "0.1.9" }
rio-proc-macros = { path = "rio-proc-macros", version = "0.1.9" }
copa = { path = "copa", default-features = true, version = "0.1.9" }
teletypewriter = { path = "teletypewriter", version = "0.1.9" }
rio-backend = { path = "rio-backend", version = "0.1.9" }
wa = { path = "wa", version = "0.1.7" }

raw-window-handle = "0.6.2"
parking_lot = "0.12.3"
rustc-hash = "2.0.0"
unicode-width = "0.1.13"
image = { version = "0.24.9", default-features = false, features = ["ico"] }
regex = "1.10.5"
bytemuck = { version = "1.17.0", features = [ "derive" ] }
log = "0.4.22"
swash = "0.1.18"
serde = { version = "1.0.208", features = ["derive"] }
tokio = { version = "1.39.3", default-features = false, features = ["rt", "rt-multi-thread", "macros"] }
wgpu = "22.1.0"
libc = "0.2.158"
smol_str = "0.2.2"
futures = "0.3.30"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.34"
wasm-bindgen-test = "0.3.42"
env_logger = "0.11.3"
console_log = "0.2.2"
bitflags = "2.6.0"
iovec = "0.1.4"
console_error_panic_hook = "0.1.7"
# winit = { package = "rio-winit-fork", path = "../rio-winit-fork", default-features = false, features = ["rwh_06"] }
winit = { package = "rio-winit-fork", version = "0.30.7", default-features = false, features = ["rwh_06"] }

[profile.release]
opt-level = 3
lto = "thin"
strip = true
debug = 0
panic = 'abort'
codegen-units = 1
incremental = false

[profile.dev]
split-debuginfo = "unpacked"
lto = false
incremental = true
opt-level = 0
