[target.wasm32-unknown-unknown]
rustflags = [
    # Enabled unstable APIs from web_sys
    "--cfg=web_sys_unstable_apis",
]
runner = 'wasm-bindgen-test-runner'

[target.aarch64-apple-darwin]
rustflags = [
    # We can guarantee that this target will always run on a CPU with _at least_
    # these capabilities, so let's optimize for them
    "-Ctarget-cpu=apple-m1"
]
