[package]
name = "teletypewriter"
description = "Rust crate to create a pseudoterminal (pty) that emulates a tty, which is a command in Unix and Unix-like operating systems to print the file name of the terminal connected to standard input. tty stands for TeleTYpewriter. This project is created and maintaned for Rio terminal purposes but feel free to use it."
version = "1.0.5"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
documentation = "https://docs.rs/crate/teletypewriter/latest"
authors = { workspace = true }

[dependencies]
libc = "0.2.140"
mio = "0.6.20"